// Tailwind preset for adsmurai-dsr-react.
// Generated by scripts/generate-tokens.mjs — do not edit by hand.
//
// OPTIONAL. The library's own components are already styled by
// `adsmurai-dsr-react/styles`; you only need this preset if you want to write
// YOUR OWN markup against the Adsmurai design tokens — the DS colour palette,
// its breakpoints (xs 576 / sm 768 / md 992 / lg 1200 / xl 1440, which are NOT
// Tailwind's defaults), radii, fonts and purple-tinted shadows.
//
// Usage:
//   import dsrPreset from 'adsmurai-dsr-react/preset';
//   export default { presets: [dsrPreset], content: ['./src/**/*.{ts,tsx}'] };
//
// Colour utilities resolve against the custom properties in
// `adsmurai-dsr-react/theme.css`, so import that too.
export default {
  "darkMode": [
    "class"
  ],
  "theme": {
    "screens": {
      "xs": "576px",
      "sm": "768px",
      "md": "992px",
      "lg": "1200px",
      "xl": "1440px"
    },
    "extend": {
      "colors": {
        "border": "hsl(var(--border) / <alpha-value>)",
        "input": "hsl(var(--input) / <alpha-value>)",
        "ring": "hsl(var(--ring) / <alpha-value>)",
        "background": "hsl(var(--background) / <alpha-value>)",
        "foreground": "hsl(var(--foreground) / <alpha-value>)",
        "primary": {
          "DEFAULT": "hsl(var(--primary) / <alpha-value>)",
          "foreground": "hsl(var(--primary-foreground) / <alpha-value>)"
        },
        "secondary": {
          "DEFAULT": "hsl(var(--secondary) / <alpha-value>)",
          "foreground": "hsl(var(--secondary-foreground) / <alpha-value>)"
        },
        "destructive": {
          "DEFAULT": "hsl(var(--destructive) / <alpha-value>)",
          "foreground": "hsl(var(--destructive-foreground) / <alpha-value>)"
        },
        "muted": {
          "DEFAULT": "hsl(var(--muted) / <alpha-value>)",
          "foreground": "hsl(var(--muted-foreground) / <alpha-value>)"
        },
        "accent": {
          "DEFAULT": "hsl(var(--accent) / <alpha-value>)",
          "foreground": "hsl(var(--accent-foreground) / <alpha-value>)"
        },
        "popover": {
          "DEFAULT": "hsl(var(--popover) / <alpha-value>)",
          "foreground": "hsl(var(--popover-foreground) / <alpha-value>)"
        },
        "card": {
          "DEFAULT": "hsl(var(--card) / <alpha-value>)",
          "foreground": "hsl(var(--card-foreground) / <alpha-value>)"
        },
        "sidebar": {
          "DEFAULT": "hsl(var(--sidebar-background))",
          "foreground": "hsl(var(--sidebar-foreground))",
          "accent": "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          "border": "hsl(var(--sidebar-border))",
          "ring": "hsl(var(--sidebar-ring))"
        },
        "chart": {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))"
        }
      },
      "borderRadius": {
        "none": "0",
        "xs": "2px",
        "sm": "4px",
        "DEFAULT": "8px",
        "md": "8px",
        "lg": "12px",
        "xl": "16px",
        "2xl": "24px",
        "3xl": "32px",
        "full": "999px"
      },
      "fontFamily": {
        "sans": [
          "\"Hanken Grotesk\"",
          "sans-serif"
        ],
        "title": [
          "\"Bricolage Grotesque\"",
          "sans-serif"
        ],
        "body": [
          "\"Hanken Grotesk\"",
          "sans-serif"
        ],
        "mono": [
          "\"IBM Plex Mono\"",
          "monospace"
        ]
      },
      "boxShadow": {
        "xs": "0 1px 1px 0 rgba(32, 14, 56, 0.07)",
        "sm": "0 1px 2px 0 rgba(32, 14, 56, 0.06), 0 2px 6px -1px rgba(32, 14, 56, 0.09)",
        "DEFAULT": "0 1px 2px 0 rgba(32, 14, 56, 0.06), 0 2px 6px -1px rgba(32, 14, 56, 0.09)",
        "md": "0 3px 8px -3px rgba(32, 14, 56, 0.08), 0 10px 28px -8px rgba(32, 14, 56, 0.15)",
        "lg": "0 10px 20px -10px rgba(32, 14, 56, 0.11), 0 28px 56px -16px rgba(32, 14, 56, 0.22)"
      },
      "spacing": {
        "ds-1": "2px",
        "ds-2": "4px",
        "ds-3": "8px",
        "ds-4": "12px",
        "ds-5": "16px",
        "ds-6": "24px",
        "ds-7": "32px",
        "ds-8": "40px",
        "ds-9": "48px"
      }
    }
  }
};
